spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bl3_client
    username: postgres
    password: 1234
    platform: postgres

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.temp.use_jdbc_metadata_defaults: false